### ISSUE TITLE
Implement BaseX hook for pull

### ISSUE THREAD

**Issue by drmacro** [dita-for-small-teams/dfst-git-commit-hooks#1]
Implement a hook that runs on pull from the remote and updates BaseX with any changed or deleted (same logic as for post-commit hook).

**Comment by markgif** [comment]
Do you want some help on this Eliot? I see you're on BaseX now instead of eXist.

**Comment by drmacro** [comment]
Yes, I decided to use BaseX for now as it makes working with DTD-based documents easier than eXist and is also generally lighter weight.

I may need help creating Windows batch versions of the bash commit hooks, but first I have to determine if it's possible make bash scripts that will work with git's trimmed down shell environment. Working that now on the basex-talk mailing list.

**Comment by drmacro** [comment]
The post-commit script now works under Windows git, so the pull version should just be a clone of that.

**Comment by markgif** [comment]
When I was working on the git hook script a while ago on Windows, I was using the bash shell that comes with git, not Windows batch files. Are you sure a Windows batch is needed?

**Comment by drmacro** [comment]
No, a windows batch file is not needed--was able to get a version of the bash script that works under Windows as well as OS X/Linux

**Comment by drmacro** [comment]
Hook is implemented. Creating additional issues for refinements.
